services:
  recuperardatos:
    build:
      context: ./BackEnd/RecuperacionDeDatos
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontenddocker:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge